### PR TITLE
[NEW FEATURE] Add the article thumbnail feature or post

### PR DESCRIPTION
**Pull request by ihzarizkyk**
made a feature update for the hugo vitae theme, namely the article or post thumbnail that I added in the partials folder and the head.html file.  besides that I added my name to the contributor

### CODE REVIEW

**Comment by dataCobra** [comment]
Thank you for this pull request.

I'll look into this and give you feedback as soon as I could test it. :+1:

**Comment by ihzarizkyk** [comment]
Thank You 😊

**Review by ihzarizkyk — COMMENTED** [review]
property="og:image"

**Comment by dataCobra** [comment]
I tested the feature and fixed the misspelling.

This feature is now available in the master branch.

Thanks you for contributing. :+1:

**Pull request merged**
